FROM trusty

MAINTAINER Richard Collins <richardc@richardc.net>

# Install NodeJS
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs-legacy
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y npm
